version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('dbt_db')}}"
    schema: staging_layer

    tables:
      - name: STG_CUSTOMER_DATA
      - name: STG_ITEMS_DATA
      - name: STG_ORDERS_DATA
      - name: STG_PAYMENTS_DATA
      - name: STG_PRODUCTS_DATA
      - name: STG_STORES_DATA
      - name: STG_SUPPLIESS_DATA
